@startuml
'https://plantuml.com/class-diagram

hide empty members

enum AbilityTriggerMode {
    RevealCell
    FlagCell
    TakeDamage
    ...
}

class AbilityHolder {
    Dictionary<AbilityTriggerMode, List<Ability>> abilities
    
    void UseAbilities(AbilityTriggerType type)
}

AbilityHolder ..> AbilityTriggerMode

class Ability {
    Sprite Icon
    string Description
    IEffect<Player> PlayerEffect
    IEffect<Grid> GridEffect
    bool IsActive
    int TimesRemain
    void Use()
}

AbilityHolder o- Ability

class Player {
    AbilityHolder AbilityHolder
    void UseAbilities(AbilityTriggerType type)
}
AbilityHolder *-- Player

@enduml