@startuml
'https://plantuml.com/class-diagram

hide empty members

class Grid
{
    Cell GetCellAt(GridIndex index)
    Task InitAsync()
    Task RevealAtAsync(GridIndex index)
    Task RevealAroundAsync(GridIndex index)
}

struct GridIndex
{
    int i
    int j
}

Grid .> GridIndex

class Cell
{
    GridIndex Index
    Grid Parent
    Cover Cover
    Flag Flag
    bool HasBomb
    CellState State
    Task Init()
    Task RevealAsync()
    Task SwitchFlagAsync()
}

Cell --> GridIndex
Cell -> CellState

enum CellStateValue
{
    Covered
    Flagged
    Revealed
}

class Flag
{
    Task LiftFlagAsync()
    Task PutDownFlagAsync()
}

class Cover
{
    Task PutCoverAsync()
    Task RevealAsync()
}

Grid *-- Cell
Cell *-- Flag
Cell *-- Cover

@enduml