@startuml
'https://plantuml.com/class-diagram

hide empty members

class Item
{
    List<ItemComponent> components
    Sprite icon
    string description
}
Item *-- ItemComponent

interface ItemComponent
{
    PlayerEffect? playerEffectOnAdd
    PlayerEffect? playerEffectOnRemove
    GridEffect? gridEffectOnAdd
    GridEffect? gridEffectOnRemove
    void OnAdd()
    void OnRemove()
}

note left of ItemComponent : T? 表示类型为 T \n的字段是可选的

interface CompositeItemComponent implements ItemComponent
{
    -List<ItemComponent> components
    void OnAdd()
    void OnRemove()
}
CompositeItemComponent *- ItemComponent

'Inventory o- Item
'
'class Inventory
'{
'    List<Item> items
'}

interface PlayerEffect
{
    void TakeOn(Player target)
}
ItemComponent o-- PlayerEffect

class Player
PlayerEffect -> Player

class Heal 
class SwitchWeapon
class Damage
class ChangeAbility
PlayerEffect <|.. Heal
PlayerEffect <|.. Damage
PlayerEffect <|... SwitchWeapon
PlayerEffect <|... ChangeAbility

interface GridEffect
{
    void Take(Grid target)
}
ItemComponent o-- GridEffect
class Grid
GridEffect -> Grid

class ChangeBombDamage
class RevealRandom
class ChangeGridColor
GridEffect <|.. ChangeBombDamage
GridEffect <|... RevealRandom
GridEffect <|.. ChangeGridColor



@enduml