@startuml
'https://plantuml.com/class-diagram

hide empty members

class Player {
    InputEventChannel InputEventChannel
    Weapon weapon
    void HandleInput(Vector2d mousePosition)
}
Weapon --* Player

class Weapon {
    Sprite Icon
    string Description
    WeaponComponent primary
    WeaponComponent secondary
    
    void UsePrimary(Cell cell)
    void UseSecondary(Cell cell)
}

abstract class WeaponComponent {
    IEffect<Player> PlayerEffect
    IEffect<Grid> GridEffect
    void Use(Cell cell)
}
Weapon *- WeaponComponent

package BasicComponents {
class Reveal extends WeaponComponent
class SwitchFlag extends WeaponComponent

}
class RevealRow extends WeaponComponent

@enduml