@startuml
'https://plantuml.com/class-diagram

hide empty members

class Item
{
    Sprite icon
    string description
    
    IEffect<Player> PlayerEffectOnAdd
    IEffect<Grid> GridEffectOnAdd
    IEffect<Player> PlayerEffectOnRemove
    IEffect<Grid> GridEffectOnRemove
    void OnAdd()
    void OnRemove()
}

Inventory o- Item

class Inventory
{
    List<Item> items
}

interface IEffect<T is Player or Grid> {
    void Take(T target)
}
Item -> IEffect
'class PlayerEffect
'class GridEffect

@enduml