@startuml
'https://plantuml.com/state-diagram

title
    单元格旗帜状态图
end title


state hidden as "隐藏"
state lift as "升旗"
state floating as "漂浮"
state put_down as "降旗"
state any as "任意状态"


[*] -> hidden

hidden --> lift : "收到升旗指令"
lift --> floating : "升旗完成"
floating --> put_down : "收到降旗指令"
put_down --> hidden : "降旗完成"

any --> [*] : "本轮游戏结束"

@enduml