@startuml

left to right direction

actor "玩家" as p1

rectangle 雷区 {

    usecase check_grid_info as "查看雷区信息"
    usecase check_bomb_remain as "查看剩余地雷数目"
    usecase check_bomb_damage as "查看地雷伤害值"
    check_grid_info ..> check_bomb_remain : <<include>>
    check_grid_info ..> check_bomb_damage : <<include>>
    
    usecase manipulate_grid as "操作雷区"
    usecase reveal_cell as "揭开单元格"
    usecase flag_cell as "标记单元格"
    manipulate_grid <.. reveal_cell : <<extend>>
    manipulate_grid <.. flag_cell : <<extend>>
    
    usecase trigger_event as "触发游戏效果"
    usecase get_item as "获得道具"
    manipulate_grid <.. trigger_event : <<extend>>
    manipulate_grid <.. get_item : <<extend>>
    
}

p1 -- check_grid_info
p1 -- manipulate_grid

@enduml
