@startuml gameplay use case
left to right direction

actor "玩家" as p1

rectangle 历史记录界面 {
    usecase check_records_list as "查看历史记录列表"
    
    usecase check_record_detail as "查看一条记录的详细信息"
    
    usecase check_seed as "查看随机数种子"
    usecase check_result as "查看对局结果"
    usecase check_items as "查看已获得的道具"
    usecase check_ability as "查看当前能力"
    usecase return_to_main_menu as "返回主菜单"
    
    check_record_detail ..> check_seed : <<include>>
    check_record_detail ..> check_result : <<include>>
    check_record_detail ..> check_items : <<include>>
    check_record_detail ..> check_ability : <<include>>
}

p1 -- check_records_list
p1 -- check_record_detail
p1 -- return_to_main_menu

@enduml