@startuml level-ui

left to right direction

actor "玩家" as p1

rectangle 关卡界面 {

    usecase (查看玩家信息) as check_player_info
    usecase (查看生命值与护甲值) as check_life
    usecase (查看已获得的道具) as check_items
    usecase (查看当前能力) as check_abilities
    usecase check_weapon as "查看当前武器"
    check_player_info ..> check_life : <<include>>
    check_player_info ..> check_items : <<include>>
    check_player_info ..> check_abilities : <<include>>
    check_player_info ..> check_weapon : <<include>>

    usecase check_level_info as "查看关卡信息"
    usecase check_level_index as "查看关卡序号"
    usecase check_level_game_mode as "查看关卡游戏模式"
    check_level_info ..> check_level_index : <<include>>
    check_level_info ..> check_level_game_mode : <<include>>

    usecase check_grid_info as "查看雷区信息"
    usecase check_bomb_remain as "查看剩余地雷数目"
    usecase check_bomb_damage as "查看地雷伤害值"
    check_grid_info ..> check_bomb_remain : <<include>>
    check_grid_info ..> check_bomb_damage : <<include>>
    
    usecase manipulate_grid as "操作雷区"
    usecase reveal_cell as "揭开单元格"
    usecase flag_cell as "标记单元格"
    manipulate_grid <.. reveal_cell : <<extend>>
    manipulate_grid <.. flag_cell : <<extend>>
    
    usecase trigger_event as "触发事件"
    usecase get_item as "获得道具"
    manipulate_grid <.. trigger_event : <<extend>>
    manipulate_grid <.. get_item : <<extend>>
    
    usecase complete_level as "完成关卡"

    usecase return_to_main_menu as "返回主菜单"
}

p1 -- check_player_info
p1 -- check_level_info
p1 -- check_grid_info
p1 -- manipulate_grid
p1 -- complete_level
p1 -- return_to_main_menu

@enduml
